fragmented project
DimaMaligon/EnglishWordXML2 pull request #1
Opened 2023-06-01 06:03 UTC by DimaMaligon

Решил сделать копию приложения на английском языке, дабы узнать, как сделать такое большое приложение на xml. 
Выбрал построение архитектуры приложени с помощью одного активити и множества лайоутов. Каждый экран определен как фрагмент. В остальном: база данных, di, viewmodel и т.д похожи на проект родитель.

2023-06-01 13:46 UTC, IvanShalimov requested changes

2023-06-01 13:46 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwordxml2/adapter/LetterAdapter.kt
> +    RecyclerView.Adapter<LetterAdapter.LetterViewHolder>() {
Ужасное форматирование, читать трудно

2023-06-01 13:46 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwordxml2/db/DbHelper.kt
> +    SQLiteOpenHelper(application, MyDataBase.DATABASE_NAME, null, MyDataBase.DATABASE_VERSION) {
Может лучше Room?

2023-06-01 13:46 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwordxml2/db/MyDbManager.kt
> +            MyDataBase.TABLE_NAME_WORDS,   // The table to query
Твои комментарии или осталось после копипасты?

2023-06-01 13:46 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwordxml2/view_model/LetterViewModel.kt
> +    private val letterMutable = MutableStateFlow("")
Невозможно разбить это на разные вью модели?

2023-06-01 13:46 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwordxml2/view_model/RepeatWordsViewModel.kt
> +                            firsKey -> true
Простого if должно хватить

2023-06-01 13:46 UTC, IvanShalimov commented on app/src/main/res/layout/fragment_dictionary.xml
> +        android:text="dictionary" />
В ресурсы следует такое выносить, если строка не нужна, то tools

2023-06-01 13:46 UTC, IvanShalimov commented on app/src/main/res/layout/fragment_main.xml
> +        android:text="Словарь"
Выноси такие тексты в ресурсы

2023-06-01 13:46 UTC, IvanShalimov commented on app/src/main/res/navigation/nav_graph.xml
> +    <fragment
Зачем так много фрагментов, а не один фрагмент контейнер?

2023-06-01 15:10 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwordxml2/adapter/LetterAdapter.kt
> +    RecyclerView.Adapter<LetterAdapter.LetterViewHolder>() {
Да я знаю, все в процессе, я же просил проверить только общее построение проекта))

2023-06-01 15:10 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwordxml2/db/MyDbManager.kt
> +            MyDataBase.TABLE_NAME_WORDS,   // The table to query
осталось после копипасты

2023-06-01 15:11 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwordxml2/view_model/LetterViewModel.kt
> +    private val letterMutable = MutableStateFlow("")
не очень понял, а зачем?

2023-06-01 15:12 UTC, DimaMaligon commented on app/src/main/res/navigation/nav_graph.xml
> +    <fragment
Я просто видел, что так делают) А как надо можешь прислать пример?

2023-06-03 09:06 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwordxml2/adapter/LetterAdapter.kt
> +    RecyclerView.Adapter<LetterAdapter.LetterViewHolder>() {
В жизни проверяют все и сразу, привыкай. Программисты слушают только себя)

2023-06-03 09:06 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwordxml2/db/MyDbManager.kt
> +            MyDataBase.TABLE_NAME_WORDS,   // The table to query
Удали, пожалуйста.

2023-06-05 05:54 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwordxml2/db/DbHelper.kt
> +    SQLiteOpenHelper(application, MyDataBase.DATABASE_NAME, null, MyDataBase.DATABASE_VERSION) {
сделаю после переноса, я так понял нужны корутины для работы с room

2023-06-05 05:59 UTC, merged